org: ptitdam2001
app: serverless-application-example
service: serverless-application-example

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  timeout: 10
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: sample/path/hello
          method: get
          cors: true

plugins:
  - serverless-offline