service: serverless-application-example

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  timeout: 10
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: index.handler
  # app:
  #   handler: index.handler
  #   events:
  #     - http: GET /
  #     - http: 'GET {proxy+}'

plugins:
  - serverless-offline